// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using customer_wellness_project.Data;

#nullable disable

namespace customer_wellness_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330230553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("customer_wellness_project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Medication",
                            MinimumThreshold = 10,
                            Name = "Insulin Humalog",
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 2,
                            Category = "Diagnostics",
                            MinimumThreshold = 50,
                            Name = "Nitrate Strips",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 3,
                            Category = "PPE",
                            MinimumThreshold = 20,
                            Name = "Surgical Masks",
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 4,
                            Category = "PPE",
                            MinimumThreshold = 50,
                            Name = "Nitrile Gloves",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 5,
                            Category = "Medication",
                            MinimumThreshold = 15,
                            Name = "Saline Solution",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("customer_wellness_project.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 30, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lab results for Patient #8829 failed to upload to portal",
                            Status = "Resolved",
                            Title = "Lab results upload failure"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 30, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ventilator unit #3 requires scheduled maintenance",
                            Status = "Urgent",
                            Title = "Emergency room equipment maintenance"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Physical count doesn't match system for insulin stock",
                            Status = "Open",
                            Title = "Pharmacy inventory discrepancy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multiple patients reporting login failures on mobile",
                            Status = "Open",
                            Title = "Patient portal access issue"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 30, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ward B monitors showing inconsistent readings",
                            Status = "Open",
                            Title = "Blood pressure monitor calibration"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Room 204 call button unresponsive",
                            Status = "Urgent",
                            Title = "Nurse call system malfunction"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 30, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronic health records taking >10s to load",
                            Status = "Open",
                            Title = "EHR system slow response"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 30, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Autoclave unit showing E-04 error code",
                            Status = "Open",
                            Title = "Sterilization unit error"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 30, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Only 2 wheelchairs available for 12-bed ward",
                            Status = "Open",
                            Title = "Wheelchair shortage Ward C"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 30, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lab refrigerator temp drifting above safe range",
                            Status = "Urgent",
                            Title = "Temperature control Lab 3"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 29, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Double booking for night shift radiology",
                            Status = "Open",
                            Title = "Shift scheduling conflict"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ventilation fan noise in MRI suite",
                            Status = "Open",
                            Title = "MRI room ventilation"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 3, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batch of amoxicillin expiring within 30 days",
                            Status = "Open",
                            Title = "Medication expiry alert"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 3, 29, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ward A nursing station printer not responding",
                            Status = "Open",
                            Title = "Network printer offline"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
